export const NOTIFICATION_CONFIG = {
  COOLDOWN_DURATION: 3000,
  CLEANUP_RETENTION_DAYS: 7,
  CLEANUP_MAX_ITEMS: 25,
  POLLING_ENABLED: true,
  POLLING_INTERVAL: 10000,
  POLLING_CHANGES_LIMIT: 5,
} as const;


